pipeline:
  build:
    image: docker.finogeeks.club/base/node-rust:16.13.1-alpine
    commands:
      - EXPORT RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup
      - EXPORT RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
      - cargo build
  docker_latest:
    image: docker.finogeeks.club/drone/docker
    repo: docker.finogeeks.club/swan/staff-profile
    dockerfile: Dockerfile
    when:
      event: [push, pull_request]
