pipeline:
  build:
    image: docker.finogeeks.club/base/node-rust:16.13.1-alpine
    commands:
      - cargo build
  docker_latest:
    image: docker.finogeeks.club/drone/docker
    repo: docker.finogeeks.club/swan/staff-profile
    dockerfile: Dockerfile
    when:
      event: [push, pull_request]
